In [4]:
import numpy as np

#Code used by making new square after new square. A different rotation to the inital one in the diagram but won't
#change the results I am looking for.

x = 36 # change here for different spiral. Must be a square number

def spiral(n):
    size = int(np.sqrt(n))
    grid = np.zeros((size, size))

    def coord(y, x):
        return 0 <= y < size and 0 <= x < size and grid[y, x] == 0

    def dist(i, j):
        return np.sqrt((i[0] - j[0]) ** 2 + (i[1] - j[1]) ** 2)

    current = (size // 2, size // 2)
    change = 1 if size % 2 == 0 else 0
    # To accomodate for odd and even cases

    for num in range(1, n + 1):
        y, x = current
        grid[y, x] = num
        unseen = [(y + dy, x + dx) for dy, dx in [(0, 1), (1, 0), (0, -1), (-1, 0)] if coord(y + dy, x + dx)]
        if num != n:
            current = min(unseen, key=lambda j: dist((size // 2 - change, size // 2 - change), j))

    return grid

def sums(spiral):
    row_sums = np.sum(spiral, axis=1)
    col_sums = np.sum(spiral, axis=0)
    return row_sums, col_sums

row_sums, col_sums = sums(spiral(x))

print(spiral(x))
print("Row sums:", row_sums)
print("Column sums:", col_sums)


[[21. 20. 19. 18. 17. 36.]
 [22.  7.  6.  5. 16. 35.]
 [23.  8.  3.  4. 15. 34.]
 [24.  9.  2.  1. 14. 33.]
 [25. 10. 11. 12. 13. 32.]
 [26. 27. 28. 29. 30. 31.]]
Row sums: [131.  91.  87.  83. 103. 171.]
Column sums: [141.  81.  69.  69. 105. 201.]
